package codegen

var (
	animals = [...]string{
		"Aardvark",
		"Aardwolf",
		"Albatross",
		"Alligator",
		"Alpaca",
		"Anaconda",
		"Andean Mountain Cat",
		"Anemone",
		"Angelfish",
		"Anole",
		"Ant",
		"Anteater",
		"Antelope",
		"Archerfish",
		"Arctic Fox",
		"Armadillo",
		"Axolotl",
		"Baboon",
		"Badger",
		"Bald Eagle",
		"Bandicoot",
		"Basilisk",
		"Bat",
		"Bear",
		"Bearded Dragon",
		"Beaver",
		"Bed Bug",
		"Bee",
		"Bee-eater",
		"Beetle",
		"Bettong",
		"Binturong",
		"Bird",
		"Bison",
		"Black-footed Cat",
		"Black-footed Ferret",
		"Blue Sheep",
		"Blue Whale",
		"Bluebird",
		"Boa",
		"Bobcat",
		"Bongo",
		"Booby",
		"Bowerbird",
		"Broadbill",
		"Brown Bear",
		"Budgie",
		"Bulbul",
		"Bull",
		"Bullfrog",
		"Bunny",
		"Bush Dog",
		"Bushbaby",
		"Bushshrike",
		"Butterfly",
		"Buzzard",
		"Camel",
		"Capybara",
		"Cardinal",
		"Cardinalfish",
		"Caribou",
		"Carp",
		"Cat",
		"Caterpillar",
		"Catfish",
		"Cattle",
		"Cavy",
		"Centipede",
		"Chameleon",
		"Cheetah",
		"Chicken",
		"Chimaera",
		"Chimpanzee",
		"Chinchilla",
		"Chipmunk",
		"ChuckWalla",
		"Cicada",
		"Clam",
		"Climbing Mouse",
		"Climbing Perch",
		"Clouded Leopard",
		"Clownfish",
		"Coati",
		"Cobra",
		"Cockatiel",
		"Cockatoo",
		"Cockroach",
		"Cotton Rat",
		"Cougar",
		"Courser",
		"Cow",
		"Coyote",
		"Crab",
		"Crane",
		"Crane Fly",
		"Crayfish",
		"Cricket",
		"Crocodile",
		"Crow",
		"Cuckoo",
		"Cuttlefish",
		"Death Adder",
		"Deer",
		"Dimetrodon",
		"Dingo",
		"Dinosaur",
		"Dipper",
		"Dodo",
		"Dog",
		"Dolphin",
		"Donkey",
		"Dormouse",
		"Dove",
		"Dragonfly",
		"Duck",
		"Dugong",
		"Eagle",
		"Echidna",
		"Eel",
		"Electric Eel",
		"Elephant",
		"Elk",
		"Emu",
		"Falcon",
		"Fennec",
		"Ferret",
		"Finch",
		"Fish",
		"Flamingo",
		"Flea",
		"Flowerpecker",
		"Fly",
		"Flying Fish",
		"Flying Frog",
		"Fox",
		"Frog",
		"Gannet",
		"Garter Snake",
		"Gazelle",
		"Gecko",
		"Gerbil",
		"Giant Panda",
		"Giant Tortoise",
		"Gibbon",
		"Giraffe",
		"Goat",
		"Goatfish",
		"Goldfish",
		"Goose",
		"Gopher",
		"Gorilla",
		"Grasshopper",
		"Green Iguana",
		"Grizzly Bear",
		"Groundhog",
		"Grouse",
		"Guinea Pig",
		"Gull",
		"Hamster",
		"Harrier",
		"Hawaiian Honeycreeper",
		"Hawk",
		"Hedgehog",
		"Hermit Crab",
		"Heron",
		"Hippopotamus",
		"Honeyeater",
		"Hornbill",
		"Hornet",
		"Horse",
		"Hoverfly",
		"Hummingbird",
		"Hyena",
		"Ibex",
		"Ibis",
		"Iguana",
		"Insect",
		"Jackal",
		"Jaguar",
		"Jay",
		"Jellyfish",
		"Jungle Cat",
		"Kangaroo",
		"Kangaroo Rat",
		"Kestrel",
		"King Cobra",
		"Kingfisher",
		"Kite",
		"Kitten",
		"Kiwi",
		"Koala",
		"Koi",
		"Komodo Dragon",
		"Ladybug",
		"Lamb",
		"Lamprey",
		"Leech",
		"Lemming",
		"Lemur",
		"Leopard",
		"Liger",
		"Lion",
		"Lionfish",
		"Lizard",
		"Llama",
		"Loach",
		"Lobster",
		"Loon",
		"Loris",
		"Lovebird",
		"Lynx",
		"Lyrebird",
		"Macaw",
		"Mallard",
		"Mamba",
		"Mammoth",
		"Manatee",
		"Mandrill",
		"Manta Ray",
		"Mantis Shrimp",
		"Marmot",
		"Marsupial Mole",
		"Marten",
		"Mastodon",
		"Meadowlark",
		"Meerkat",
		"Megapode",
		"Millipede",
		"Miniature Horse",
		"Mink",
		"Minnow",
		"Mockingbird",
		"Mole",
		"Mole Rat",
		"Mongoose",
		"Monitor Lizard",
		"Monkey",
		"Moorhen",
		"Moose",
		"Moray Eel",
		"Mosasaur",
		"Mosquito",
		"Moth",
		"Mountain Goat",
		"Mountain Lion",
		"Mouse",
		"Mouse Deer",
		"Mousebird",
		"Mudpuppy",
		"Mudskipper",
		"Mullet",
		"muskrat",
		"Musky Rat-Kangaroo",
		"Naked Mole-rat",
		"Narwhal",
		"Nautilus",
		"Needlefish",
		"Newt",
		"Nighthawk",
		"Ocelot",
		"Octopus",
		"Opossum",
		"Orangutan",
		"Orca",
		"Oryx",
		"Osprey",
		"Ostrich",
		"Otter",
		"Owl",
		"Oyster",
		"Paddlefish",
		"Panda",
		"Pangolin",
		"Panther",
		"Parakeet",
		"Parrot",
		"Parrotfish",
		"Passenger Pigeon",
		"Peacock",
		"Peafowl",
		"Pelican",
		"Penguin",
		"Pheasant",
		"Pig",
		"Pigeon",
		"Pike",
		"Piranha",
		"Platypus",
		"Poison Dart Frog",
		"Polar Bear",
		"Pony",
		"Porcupine",
		"Porpoise",
		"Possum",
		"Pouched Rat",
		"Prairie Dog",
		"Prawn",
		"Praying Mantis",
		"Pronghorn",
		"Puffer Fish",
		"Puffin",
		"Puma",
		"Puppy",
		"Python",
		"Quail",
		"Rabbit",
		"Raccoon",
		"Rainbowfish",
		"Rat",
		"Rattlesnake",
		"Raven",
		"Red Panda",
		"Reindeer",
		"Rhea",
		"Rhinoceros",
		"Roadrunner",
		"Robin",
		"Rockfish",
		"Rook",
		"Sailfish",
		"Salamander",
		"Salmon",
		"Sandgrouse",
		"Sawfish",
		"Scorpion",
		"Sea Anemone",
		"Sea Cucumber",
		"Sea Duck",
		"Sea Gull",
		"Sea Lion",
		"Sea Otter",
		"Sea Snake",
		"Seadragon",
		"Seahorse",
		"Seal",
		"Shark",
		"Sheep",
		"Shrew",
		"Shrimp",
		"Skate",
		"Skink",
		"Skunk",
		"Sloth",
		"Sloth Bear",
		"Slow Loris",
		"Slug",
		"Snail",
		"Snake",
		"Snow Leopard",
		"Songbird",
		"Sparrow",
		"Spider",
		"Sponge",
		"Spoonbill",
		"Squid",
		"Squirrel",
		"Starfish",
		"Starling",
		"Stingray",
		"Stoat",
		"Stonefish",
		"Stork",
		"Sturgeon",
		"Sun Bear",
		"Sunbird",
		"Surgeonfish",
		"Swallow",
		"Swan",
		"Swift",
		"Swordfish",
		"Tadpole",
		"Tamarin",
		"Tapir",
		"Tarantula",
		"Tasmanian Devil",
		"Tasmanian Wolf",
		"Termite",
		"Thornbill",
		"Thrush",
		"Tiger",
		"Toad",
		"Tortoise",
		"Toucan",
		"Treeshrew",
		"T-Rex",
		"Trout",
		"Tuna",
		"Turkey",
		"Turtle",
		"Urchin",
		"Viper",
		"Vole",
		"Vulture",
		"Wader",
		"Wagtail",
		"Wallaby",
		"Walrus",
		"Warbler",
		"Warthog",
		"Wasp",
		"Water Buffalo",
		"Weasel",
		"Whale",
		"Widow Spider",
		"Wildcat",
		"Wildebeest",
		"Wolf",
		"Wolverine",
		"Wombat",
		"Woodchuck",
		"Woodcock",
		"Woodpecker",
		"Woodswallow",
		"Worm",
		"Wren",
		"Xenops",
		"Xerus",
		"Yak",
		"Yapok",
		"Zebra",
		"Zebu",
	}

	colours = [...]string{
		"Absolute Zero",
		"Acid",
		"Acid green",
		"Aero",
		"Aero blue",
		"Air superiority blue",
		"Alabama crimson",
		"Alabaster",
		"Alice blue",
		"Alien Armpit",
		"Alloy orange",
		"Almond",
		"Amazon",
		"Amber",
		"Amethyst",
		"Anti-flash white",
		"Antique brass",
		"Antique bronze",
		"Antique fuchsia",
		"Antique ruby",
		"Antique white",
		"Ao",
		"Apple green",
		"Apricot",
		"Aqua",
		"Aquamarine",
		"Arctic lime",
		"Army green",
		"Artichoke",
		"Arylide yellow",
		"Ash gray",
		"Asparagus",
		"Atomic tangerine",
		"Auburn",
		"Aureolin",
		"Avocado",
		"Azure",
		"Azure mist",
		"Baby blue",
		"Baby blue eyes",
		"Baby pink",
		"Baby powder",
		"Baker-Miller pink",
		"Banana Mania",
		"Barbie Pink",
		"Barn red",
		"Battleship grey",
		"Beau blue",
		"Beaver",
		"Beige",
		"B'dazzled blue",
		"Big dip o’ruby",
		"Big Foot Feet",
		"Bisque",
		"Bistre",
		"Bistre brown",
		"Bitter lemon",
		"Bitter lime",
		"Bittersweet",
		"Bittersweet shimmer",
		"Black",
		"Black bean",
		"Black chocolate",
		"Black coffee",
		"Black coral",
		"Black olive",
		"Black Shadows",
		"Blanched almond",
		"Blast-off bronze",
		"Bleu de France",
		"Blizzard blue",
		"Blond",
		"Blood red",
		"Blue",
		"Blue bell",
		"Blue-gray",
		"Blue-green",
		"Blue jeans",
		"Blue sapphire",
		"Blue-violet",
		"Blue yonder",
		"Bluetiful",
		"Blush",
		"Bole",
		"Bondi blue",
		"Bone",
		"Bottle green",
		"Brandy",
		"Brick red",
		"Bright green",
		"Bright lilac",
		"Bright maroon",
		"Bright navy blue",
		"Bright yellow",
		"Brilliant rose",
		"Brink pink",
		"British racing green",
		"Bronze",
		"Brown",
		"Brown sugar",
		"Brunswick green",
		"Bubbles",
		"Bud green",
		"Buff",
		"Burgundy",
		"Burlywood",
		"Burnished brown",
		"Burnt orange",
		"Burnt sienna",
		"Burnt umber",
		"Byzantine",
		"Byzantium",
		"Cadet",
		"Cadet blue",
		"Cadet grey",
		"Cadmium green",
		"Cadmium orange",
		"Cadmium red",
		"Cadmium yellow",
		"Cambridge blue",
		"Camel",
		"Cameo pink",
		"Canary",
		"Canary yellow",
		"Candy apple red",
		"Candy pink",
		"Capri",
		"Caput mortuum",
		"Cardinal",
		"Caribbean green",
		"Carmine",
		"Carnation pink",
		"Carnelian",
		"Carolina blue",
		"Carrot orange",
		"Castleton green",
		"Catawba",
		"Cedar Chest",
		"Celadon",
		"Celadon blue",
		"Celadon green",
		"Celeste",
		"Celtic blue",
		"Cerise",
		"Cerulean",
		"Cerulean blue",
		"Cerulean frost",
		"CG blue",
		"CG red",
		"Champagne",
		"Champagne pink",
		"Charcoal",
		"Charleston green",
		"Charm pink",
		"Chartreuse",
		"Cherry blossom pink",
		"Chestnut",
		"China pink",
		"China rose",
		"Chinese red",
		"Chinese violet",
		"Chinese yellow",
		"Chocolate",
		"Chrome yellow",
		"Cinereous",
		"Cinnabar",
		"Cinnamon Satin",
		"Citrine",
		"Citron",
		"Claret",
		"Cobalt blue",
		"Cocoa brown",
		"Coffee",
		"Columbia Blue",
		"Congo pink",
		"Cool grey",
		"Copper",
		"Copper penny",
		"Copper red",
		"Copper rose",
		"Coquelicot",
		"Coral",
		"Coral pink",
		"Cordovan",
		"Corn",
		"Cornflower blue",
		"Cornsilk",
		"Cosmic cobalt",
		"Cosmic latte",
		"Cosmos pink",
		"Coyote brown",
		"Cotton candy",
		"Cream",
		"Crimson",
		"Cultured",
		"Cyan",
		"Cyber grape",
		"Cyber yellow",
		"Cyclamen",
		"Dark blue-gray",
		"Dark brown",
		"Dark byzantium",
		"Dark cornflower blue",
		"Dark cyan",
		"Dark electric blue",
		"Dark goldenrod",
		"Dark green",
		"Dark jungle green",
		"Dark khaki",
		"Dark lava",
		"Dark liver",
		"Dark magenta",
		"Dark moss green",
		"Dark olive green",
		"Dark orange",
		"Dark orchid",
		"Dark pastel green",
		"Dark purple",
		"Dark red",
		"Dark salmon",
		"Dark sea green",
		"Dark sienna",
		"Dark sky blue",
		"Dark slate blue",
		"Dark slate gray",
		"Dark spring green",
		"Dark turquoise",
		"Dark violet",
		"Dartmouth green",
		"Deep cerise",
		"Deep champagne",
		"Deep chestnut",
		"Deep jungle green",
		"Deep pink",
		"Deep saffron",
		"Deep sky blue",
		"Deep Space Sparkle",
		"Deep taupe",
		"Denim",
		"Denim blue",
		"Desert",
		"Desert sand",
		"Dim gray",
		"Dingy Dungeon",
		"Dodger blue",
		"Dogwood rose",
		"Drab",
		"Duke blue",
		"Dutch white",
		"Earth yellow",
		"Ebony",
		"Ecru",
		"Eerie black",
		"Eggplant",
		"Eggshell",
		"Egyptian blue",
		"Electric blue",
		"Electric green",
		"Electric indigo",
		"Electric lime",
		"Electric purple",
		"Electric violet",
		"Emerald",
		"Eminence",
		"English green",
		"English lavender",
		"English red",
		"English vermillion",
		"English violet",
		"Erin",
		"Eton blue",
		"Fallow",
		"Falu red",
		"Fandango",
		"Fandango pink",
		"Fashion fuchsia",
		"Fawn",
		"Feldgrau",
		"Fern green",
		"Field drab",
		"Fiery rose",
		"Firebrick",
		"Fire engine red",
		"Fire opal",
		"Flame",
		"Flax",
		"Flesh",
		"Flickr Blue",
		"Flickr Pink",
		"Flirt",
		"Floral white",
		"Fluorescent blue",
		"Forest green",
		"French beige",
		"French bistre",
		"French blue",
		"French fuchsia",
		"French lilac",
		"French lime",
		"French mauve",
		"French pink",
		"French raspberry",
		"French rose",
		"French sky blue",
		"French violet",
		"Frostbite",
		"Fuchsia",
		"Fuchsia purple",
		"Fuchsia rose",
		"Fulvous",
		"Fuzzy Wuzzy",
		"Gainsboro",
		"Gamboge",
		"Gamboge orange",
		"Gargoyle Gas",
		"Generic viridian",
		"Ghost white",
		"Glaucous",
		"Glossy grape",
		"GO green",
		"Gold",
		"Gold Fusion",
		"Golden brown",
		"Golden poppy",
		"Golden yellow",
		"Goldenrod",
		"Granite gray",
		"Granny Smith apple",
		"Gray",
		"Green",
		"Green-blue",
		"Green-cyan",
		"Green Lizard",
		"Green Sheen",
		"Green-yellow",
		"Grullo",
		"Gunmetal",
		"Han blue",
		"Han purple",
		"Hansa yellow",
		"Harlequin",
		"Harvest gold",
		"Heat Wave",
		"Heliotrope",
		"Heliotrope gray",
		"Hollywood cerise",
		"Honeydew",
		"Honolulu blue",
		"Hot magenta",
		"Hot pink",
		"Hunter green",
		"Iceberg",
		"Icterine",
		"Illuminating emerald",
		"Imperial red",
		"Inchworm",
		"Independence",
		"India green",
		"Indian red",
		"Indian yellow",
		"Indigo",
		"Indigo blue",
		"Indigo dye",
		"International Klein Blue",
		"International orange",
		"Iris",
		"Irresistible",
		"Isabelline",
		"Islamic green",
		"Italian sky blue",
		"Ivory",
		"Jade",
		"Jasmine",
		"Jazzberry jam",
		"Jet",
		"Jonquil",
		"June bud",
		"Jungle green",
		"Kelly green",
		"Keppel",
		"Key lime",
		"Khaki",
		"Kobe",
		"Kobi",
		"Kobicha",
		"Kombu green",
		"KSU purple",
		"Languid lavender",
		"Lapis lazuli",
		"Laser lemon",
		"Laurel green",
		"Lava",
		"Lavender",
		"Lavender blue",
		"Lavender blush",
		"Lavender gray",
		"Lavender magenta",
		"Lawn green",
		"Lemon",
		"Lemon chiffon",
		"Lemon curry",
		"Lemon glacier",
		"Lemon meringue",
		"Lemon yellow",
		"Liberty",
		"Light blue",
		"Light coral",
		"Light cornflower blue",
		"Light cyan",
		"Light French beige",
		"Light goldenrod yellow",
		"Light gray",
		"Light green",
		"Light orange",
		"Light periwinkle",
		"Light pink",
		"Light salmon",
		"Light sea green",
		"Light sky blue",
		"Light slate gray",
		"Light steel blue",
		"Light yellow",
		"Lilac",
		"Lilac Luster",
		"Lime",
		"Lime green",
		"Lincoln green",
		"Linen",
		"Lion",
		"Liseran purple",
		"Little boy blue",
		"Liver",
		"Liver chestnut",
		"Livid",
		"Macaroni and Cheese",
		"Madder Lake",
		"Magenta",
		"Magenta haze",
		"Magic mint",
		"Magnolia",
		"Mahogany",
		"Maize",
		"Majorelle blue",
		"Malachite",
		"Manatee",
		"Mandarin",
		"Mango",
		"Mango Tango",
		"Mantis",
		"Mardi Gras",
		"Marigold",
		"Maroon",
		"Mauve",
		"Mauve taupe",
		"Mauvelous",
		"Maximum blue",
		"Maximum blue green",
		"Maximum blue purple",
		"Maximum green",
		"Maximum green yellow",
		"Maximum purple",
		"Maximum red",
		"Maximum yellow",
		"Maximum yellow red",
		"May green",
		"Maya blue",
		"Medium aquamarine",
		"Medium blue",
		"Medium candy apple red",
		"Medium carmine",
		"Medium champagne",
		"Medium orchid",
		"Medium purple",
		"Medium sea green",
		"Medium slate blue",
		"Medium spring green",
		"Medium turquoise",
		"Medium violet-red",
		"Mellow apricot",
		"Mellow yellow",
		"Melancholy",
		"Melon",
		"Metallic gold",
		"Metallic Seaweed",
		"Metallic Sunburst",
		"Mexican pink",
		"Middle blue",
		"Middle blue green",
		"Middle blue purple",
		"Middle grey",
		"Middle green",
		"Middle green yellow",
		"Middle purple",
		"Middle red",
		"Middle red purple",
		"Middle yellow",
		"Middle yellow red",
		"Midnight",
		"Midnight blue",
		"Midnight green",
		"Mikado yellow",
		"Mimi pink",
		"Mindaro",
		"Ming",
		"Minion yellow",
		"Mint",
		"Mint cream",
		"Mint green",
		"Misty moss",
		"Misty rose",
		"Mode beige",
		"Morning blue",
		"Moss green",
		"Mountain Meadow",
		"Mountbatten pink",
		"MSU green",
		"Mulberry",
		"Mustard",
		"Myrtle green",
		"Mystic",
		"Mystic maroon",
		"Nadeshiko pink",
		"Naples yellow",
		"Navajo white",
		"Navy blue",
		"Neon blue",
		"Neon green",
		"New York pink",
		"Nickel",
		"Nintendo red",
		"Non-photo blue",
		"Nyanza",
		"Ocean Blue",
		"Ocean green",
		"Ochre",
		"Old burgundy",
		"Old gold",
		"Old lace",
		"Old lavender",
		"Old mauve",
		"Old rose",
		"Old silver",
		"Olive",
		"Olive Drab",
		"Olive green",
		"Olivine",
		"Onyx",
		"Opal",
		"Opera mauve",
		"Orange",
		"Orange peel",
		"Orange-red",
		"Orange soda",
		"Orange-yellow",
		"Orchid",
		"Orchid pink",
		"Outer space",
		"Outrageous Orange",
		"Oxblood",
		"Oxford blue",
		"OU Crimson red",
		"Pacific blue",
		"Pakistan green",
		"Palatinate purple",
		"Pale aqua",
		"Pale cerulean",
		"Pale pink",
		"Pale purple",
		"Pale silver",
		"Pale spring bud",
		"Pansy purple",
		"Paolo Veronese green",
		"Papaya whip",
		"Paradise pink",
		"Paris Green",
		"Pastel pink",
		"Patriarch",
		"Peach",
		"Peach",
		"Peach puff",
		"Pear",
		"Pearly purple",
		"Periwinkle",
		"Permanent Geranium Lake",
		"Persian blue",
		"Persian green",
		"Persian indigo",
		"Persian orange",
		"Persian pink",
		"Persian plum",
		"Persian red",
		"Persian rose",
		"Persimmon",
		"Pewter Blue",
		"Phlox",
		"Phthalo blue",
		"Phthalo green",
		"Picotee blue",
		"Pictorial carmine",
		"Piggy pink",
		"Pine green",
		"Pine tree",
		"Pink",
		"Pink flamingo",
		"Pink lace",
		"Pink lavender",
		"Pink Sherbet",
		"Pistachio",
		"Platinum",
		"Plum",
		"Plump Purple",
		"Polished Pine",
		"Pomp and Power",
		"Popstar",
		"Portland Orange",
		"Powder blue",
		"Princess Perfume",
		"Princeton orange",
		"Prune",
		"Prussian blue",
		"Psychedelic purple",
		"Puce",
		"Pullman Brown",
		"Pumpkin",
		"Purple",
		"Purple mountain majesty",
		"Purple navy",
		"Purple pizzazz",
		"Purple Plum",
		"Purpureus",
		"Queen blue",
		"Queen pink",
		"Quick Silver",
		"Quinacridone magenta",
		"Radical Red",
		"Raisin black",
		"Rajah",
		"Raspberry",
		"Raspberry glace",
		"Raspberry rose",
		"Raw Sienna",
		"Raw umber",
		"Razzle dazzle rose",
		"Razzmatazz",
		"Razzmic Berry",
		"Rebecca Purple",
		"Red",
		"Red-orange",
		"Red-purple",
		"Red Salsa",
		"Red-violet",
		"Redwood",
		"Resolution blue",
		"Rhythm",
		"Rich black",
		"Rifle green",
		"Robin egg blue",
		"Rocket metallic",
		"Roman silver",
		"Rose",
		"Rose bonbon",
		"Rose Dust",
		"Rose ebony",
		"Rose madder",
		"Rose pink",
		"Rose quartz",
		"Rose red",
		"Rose taupe",
		"Rose vale",
		"Rosewood",
		"Rosso corsa",
		"Rosy brown",
		"Royal blue",
		"Royal purple",
		"Royal yellow",
		"Ruber",
		"Rubine red",
		"Ruby",
		"Ruby red",
		"Rufous",
		"Russet",
		"Russian green",
		"Russian violet",
		"Rust",
		"Rusty red",
		"Sacramento State green",
		"Saddle brown",
		"Safety orange",
		"Safety yellow",
		"Saffron",
		"Sage",
		"Salmon",
		"Salmon pink",
		"Sand",
		"Sand dune",
		"Sandy brown",
		"Sap green",
		"Sapphire",
		"Sapphire blue",
		"Satin sheen gold",
		"Scarlet",
		"Schauss pink",
		"School bus yellow",
		"Sea green",
		"Seal brown",
		"Seashell",
		"Selective yellow",
		"Sepia",
		"Shadow",
		"Shadow blue",
		"Shamrock green",
		"Sheen green",
		"Shimmering Blush",
		"Shiny Shamrock",
		"Shocking pink",
		"Sienna",
		"Silver",
		"Silver chalice",
		"Silver pink",
		"Silver sand",
		"Sinopia",
		"Sizzling Red",
		"Sizzling Sunrise",
		"Skobeloff",
		"Sky blue",
		"Sky magenta",
		"Slate blue",
		"Slate gray",
		"Slimy green",
		"Smitten",
		"Smoky black",
		"Snow",
		"Solid pink",
		"Sonic silver",
		"Space cadet",
		"Spanish bistre",
		"Spanish blue",
		"Spanish carmine",
		"Spanish gray",
		"Spanish green",
		"Spanish orange",
		"Spanish pink",
		"Spanish red",
		"Spanish sky blue",
		"Spanish violet",
		"Spanish viridian",
		"Spring bud",
		"Spring Frost",
		"Spring green",
		"Star command blue",
		"Steel blue",
		"Steel pink",
		"Steel Teal",
		"Stil de grain yellow",
		"Straw",
		"Sugar Plum",
		"Sunglow",
		"Sunray",
		"Sunset",
		"Super pink",
		"Sweet Brown",
		"Tan",
		"Tangerine",
		"Tango pink",
		"Tart Orange",
		"Taupe",
		"Taupe gray",
		"Tea green",
		"Tea rose",
		"Tea rose",
		"Teal",
		"Teal blue",
		"Telemagenta",
		"Terra cotta",
		"Thistle",
		"Thulian pink",
		"Tickle Me Pink",
		"Tiffany Blue",
		"Timberwolf",
		"Titanium yellow",
		"Tomato",
		"Tropical rain forest",
		"True Blue",
		"Tufts blue",
		"Tumbleweed",
		"Turquoise",
		"Turquoise blue",
		"Turquoise green",
		"Turtle green",
		"Tuscan",
		"Tuscan brown",
		"Tuscan red",
		"Tuscan tan",
		"Tuscany",
		"Twilight lavender",
		"Tyrian purple",
		"UA blue",
		"UA red",
		"Ultramarine",
		"Ultramarine blue",
		"Ultra pink",
		"Ultra red",
		"Umber",
		"Unbleached silk",
		"United Nations blue",
		"Unmellow yellow",
		"UP Forest green",
		"UP maroon",
		"Upsdell red",
		"Uranian blue",
		"USAFA blue",
		"Van Dyke brown",
		"Vanilla",
		"Vanilla ice",
		"Vegas gold",
		"Venetian red",
		"Verdigris",
		"Vermilion",
		"Vermilion",
		"Veronica",
		"Violet",
		"Violet-blue",
		"Violet-red",
		"Violet-red",
		"Viridian",
		"Viridian green",
		"Vivid burgundy",
		"Vivid sky blue",
		"Vivid tangerine",
		"Vivid violet",
		"Volt",
		"Warm black",
		"Wheat",
		"White",
		"Wild blue yonder",
		"Wild orchid",
		"Wild Strawberry",
		"Wild watermelon",
		"Windsor tan",
		"Wine",
		"Wine dregs",
		"Winter Sky",
		"Wintergreen Dream",
		"Wisteria",
		"Wood brown",
		"Yale Blue",
		"Yellow",
		"Yellow-green",
		"Yellow Orange",
		"Yellow Sunshine",
		"YInMn Blue",
		"Zaffre",
		"Zomp",
	}

	adjectives = [...]string{
		"aback",
		"abaft",
		"abandoned",
		"abashed",
		"aberrant",
		"abhorrent",
		"abiding",
		"abject",
		"ablaze",
		"able",
		"abnormal",
		"aboard",
		"aboriginal",
		"abortive",
		"abounding",
		"abrasive",
		"abrupt",
		"absent",
		"absorbed",
		"absorbing",
		"abstracted",
		"absurd",
		"abundant",
		"abusive",
		"acceptable",
		"accessible",
		"accidental",
		"accurate",
		"acid",
		"acidic",
		"acoustic",
		"acrid",
		"actually",
		"adhoc",
		"adamant",
		"adaptable",
		"addicted",
		"adhesive",
		"adjoining",
		"adorable",
		"adventurous",
		"afraid",
		"aggressive",
		"agonizing",
		"agreeable",
		"ahead",
		"ajar",
		"alcoholic",
		"alert",
		"alike",
		"alive",
		"alleged",
		"alluring",
		"aloof",
		"amazing",
		"ambiguous",
		"ambitious",
		"amuck",
		"amused",
		"amusing",
		"ancient",
		"angry",
		"animated",
		"annoyed",
		"annoying",
		"anxious",
		"apathetic",
		"aquatic",
		"aromatic",
		"arrogant",
		"ashamed",
		"aspiring",
		"assorted",
		"astonishing",
		"attractive",
		"auspicious",
		"automatic",
		"available",
		"average",
		"awake",
		"aware",
		"awesome",
		"awful",
		"axiomatic",
		"bad",
		"barbarous",
		"bashful",
		"bawdy",
		"beautiful",
		"befitting",
		"belligerent",
		"beneficial",
		"bent",
		"berserk",
		"best",
		"better",
		"bewildered",
		"big",
		"billowy",
		"bite-sized",
		"bitter",
		"bizarre",
		"black",
		"black-and-white",
		"bloody",
		"blue",
		"blue-eyed",
		"blushing",
		"boiling",
		"boorish",
		"bored",
		"boring",
		"bouncy",
		"boundless",
		"brainy",
		"brash",
		"brave",
		"brawny",
		"breakable",
		"breezy",
		"brief",
		"bright",
		"bright",
		"broad",
		"broken",
		"brown",
		"bumpy",
		"burly",
		"bustling",
		"busy",
		"cagey",
		"calculating",
		"callous",
		"calm",
		"capable",
		"capricious",
		"careful",
		"careless",
		"caring",
		"cautious",
		"ceaseless",
		"certain",
		"changeable",
		"charming",
		"cheap",
		"cheerful",
		"chemical",
		"chief",
		"childlike",
		"chilly",
		"chivalrous",
		"chubby",
		"chunky",
		"clammy",
		"classy",
		"clean",
		"clear",
		"clever",
		"cloistered",
		"cloudy",
		"closed",
		"clumsy",
		"cluttered",
		"coherent",
		"cold",
		"colorful",
		"colossal",
		"combative",
		"comfortable",
		"common",
		"complete",
		"complex",
		"concerned",
		"condemned",
		"confused",
		"conscious",
		"cooing",
		"cool",
		"cooperative",
		"coordinated",
		"courageous",
		"cowardly",
		"crabby",
		"craven",
		"crazy",
		"creepy",
		"crooked",
		"crowded",
		"cruel",
		"cuddly",
		"cultured",
		"cumbersome",
		"curious",
		"curly",
		"curved",
		"curvy",
		"cut",
		"cute",
		"cute",
		"cynical",
		"daffy",
		"daily",
		"damaged",
		"damaging",
		"damp",
		"dangerous",
		"dapper",
		"dark",
		"dashing",
		"dazzling",
		"dead",
		"deadpan",
		"deafening",
		"dear",
		"debonair",
		"decisive",
		"decorous",
		"deep",
		"deeply",
		"defeated",
		"defective",
		"defiant",
		"delicate",
		"delicious",
		"delightful",
		"demonic",
		"delirious",
		"dependent",
		"depressed",
		"deranged",
		"descriptive",
		"deserted",
		"detailed",
		"determined",
		"devilish",
		"didactic",
		"different",
		"difficult",
		"diligent",
		"direful",
		"dirty",
		"disagreeable",
		"disastrous",
		"discreet",
		"disgusted",
		"disgusting",
		"disillusioned",
		"dispensable",
		"distinct",
		"disturbed",
		"divergent",
		"dizzy",
		"domineering",
		"doubtful",
		"drab",
		"draconian",
		"dramatic",
		"dreary",
		"drunk",
		"dry",
		"dull",
		"dusty",
		"dusty",
		"dynamic",
		"dysfunctional",
		"eager",
		"early",
		"earsplitting",
		"earthy",
		"easy",
		"eatable",
		"economic",
		"educated",
		"efficacious",
		"efficient",
		"eight",
		"elastic",
		"elated",
		"elderly",
		"electric",
		"elegant",
		"elfin",
		"elite",
		"embarrassed",
		"eminent",
		"empty",
		"enchanted",
		"enchanting",
		"encouraging",
		"endurable",
		"energetic",
		"enormous",
		"entertaining",
		"enthusiastic",
		"envious",
		"equable",
		"equal",
		"erect",
		"erratic",
		"ethereal",
		"evanescent",
		"evasive",
		"even",
		"excellent",
		"excited",
		"exciting",
		"exclusive",
		"exotic",
		"expensive",
		"extra-large",
		"extra-small",
		"exuberant",
		"exultant",
		"fabulous",
		"faded",
		"faint",
		"fair",
		"faithful",
		"fallacious",
		"false",
		"familiar",
		"famous",
		"fanatical",
		"fancy",
		"fantastic",
		"far",
		"far-flung",
		"fascinated",
		"fast",
		"fat",
		"faulty",
		"fearful",
		"fearless",
		"feeble",
		"feigned",
		"female",
		"fertile",
		"festive",
		"few",
		"fierce",
		"filthy",
		"fine",
		"finicky",
		"first",
		"five",
		"fixed",
		"flagrant",
		"flaky",
		"flashy",
		"flat",
		"flawless",
		"flimsy",
		"flippant",
		"flowery",
		"fluffy",
		"fluttering",
		"foamy",
		"foolish",
		"foregoing",
		"forgetful",
		"fortunate",
		"four",
		"frail",
		"fragile",
		"frantic",
		"free",
		"freezing",
		"frequent",
		"fresh",
		"fretful",
		"friendly",
		"frightened",
		"frightening",
		"full",
		"fumbling",
		"functional",
		"funny",
		"furry",
		"furtive",
		"future",
		"futuristic",
		"fuzzy",
		"gabby",
		"gainful",
		"gamy",
		"gaping",
		"garrulous",
		"gaudy",
		"general",
		"gentle",
		"giant",
		"giddy",
		"gifted",
		"gigantic",
		"glamorous",
		"gleaming",
		"glib",
		"glistening",
		"glorious",
		"glossy",
		"godly",
		"good",
		"goofy",
		"gorgeous",
		"graceful",
		"grandiose",
		"grateful",
		"gratis",
		"gray",
		"greasy",
		"great",
		"greedy",
		"green",
		"grey",
		"grieving",
		"groovy",
		"grotesque",
		"grouchy",
		"grubby",
		"gruesome",
		"grumpy",
		"guarded",
		"guiltless",
		"gullible",
		"gusty",
		"guttural",
		"habitual",
		"half",
		"hallowed",
		"halting",
		"handsome",
		"handsomely",
		"handy",
		"hanging",
		"hapless",
		"happy",
		"hard",
		"hard-to-find",
		"harmonious",
		"harsh",
		"hateful",
		"heady",
		"healthy",
		"heartbreaking",
		"heavenly",
		"heavy",
		"hellish",
		"helpful",
		"helpless",
		"hesitant",
		"hideous",
		"high",
		"highfalutin",
		"high-pitched",
		"hilarious",
		"hissing",
		"historical",
		"holistic",
		"hollow",
		"homeless",
		"homely",
		"honorable",
		"horrible",
		"hospitable",
		"hot",
		"huge",
		"hulking",
		"humdrum",
		"humorous",
		"hungry",
		"hurried",
		"hurt",
		"hushed",
		"husky",
		"hypnotic",
		"hysterical",
		"icky",
		"icy",
		"idiotic",
		"ignorant",
		"ill",
		"illegal",
		"ill-fated",
		"ill-informed",
		"illustrious",
		"imaginary",
		"immense",
		"imminent",
		"impartial",
		"imperfect",
		"impolite",
		"important",
		"imported",
		"impossible",
		"incandescent",
		"incompetent",
		"inconclusive",
		"industrious",
		"incredible",
		"inexpensive",
		"infamous",
		"innate",
		"innocent",
		"inquisitive",
		"insidious",
		"instinctive",
		"intelligent",
		"interesting",
		"internal",
		"invincible",
		"irate",
		"irritating",
		"itchy",
		"jaded",
		"jagged",
		"jazzy",
		"jealous",
		"jittery",
		"jobless",
		"jolly",
		"joyous",
		"judicious",
		"juicy",
		"jumbled",
		"jumpy",
		"juvenile",
		"kaput",
		"keen",
		"kind",
		"kindhearted",
		"kindly",
		"knotty",
		"knowing",
		"knowledgeable",
		"known",
		"labored",
		"lackadaisical",
		"lacking",
		"lame",
		"lamentable",
		"languid",
		"large",
		"last",
		"late",
		"laughable",
		"lavish",
		"lazy",
		"lean",
		"learned",
		"left",
		"legal",
		"lethal",
		"level",
		"lewd",
		"light",
		"like",
		"likeable",
		"limping",
		"literate",
		"little",
		"lively",
		"lively",
		"living",
		"lonely",
		"long",
		"longing",
		"long-term",
		"loose",
		"lopsided",
		"loud",
		"loutish",
		"lovely",
		"loving",
		"low",
		"lowly",
		"lucky",
		"ludicrous",
		"lumpy",
		"lush",
		"luxuriant",
		"lying",
		"lyrical",
		"macabre",
		"macho",
		"maddening",
		"madly",
		"magenta",
		"magical",
		"magnificent",
		"majestic",
		"makeshift",
		"male",
		"malicious",
		"mammoth",
		"maniacal",
		"many",
		"marked",
		"massive",
		"married",
		"marvelous",
		"material",
		"materialistic",
		"mature",
		"mean",
		"measly",
		"meaty",
		"medical",
		"meek",
		"mellow",
		"melodic",
		"melted",
		"merciful",
		"mere",
		"messy",
		"mighty",
		"military",
		"milky",
		"mindless",
		"miniature",
		"minor",
		"miscreant",
		"misty",
		"mixed",
		"moaning",
		"modern",
		"moldy",
		"momentous",
		"motionless",
		"mountainous",
		"muddled",
		"mundane",
		"murky",
		"mushy",
		"mute",
		"mysterious",
		"naive",
		"nappy",
		"narrow",
		"nasty",
		"natural",
		"naughty",
		"nauseating",
		"near",
		"neat",
		"nebulous",
		"necessary",
		"needless",
		"needy",
		"neighborly",
		"nervous",
		"new",
		"next",
		"nice",
		"nifty",
		"nimble",
		"nine",
		"nippy",
		"noiseless",
		"noisy",
		"nonchalant",
		"nondescript",
		"nonstop",
		"normal",
		"nostalgic",
		"nosy",
		"noxious",
		"null",
		"numberless",
		"numerous",
		"nutritious",
		"nutty",
		"oafish",
		"obedient",
		"obeisant",
		"obese",
		"obnoxious",
		"obscene",
		"obsequious",
		"observant",
		"obsolete",
		"obtainable",
		"oceanic",
		"odd",
		"offbeat",
		"old",
		"old-fashioned",
		"omniscient",
		"one",
		"onerous",
		"open",
		"opposite",
		"optimal",
		"orange",
		"ordinary",
		"organic",
		"ossified",
		"outgoing",
		"outrageous",
		"outstanding",
		"oval",
		"overconfident",
		"overjoyed",
		"overrated",
		"overt",
		"overwrought",
		"painful",
		"painstaking",
		"pale",
		"paltry",
		"panicky",
		"panoramic",
		"parallel",
		"parched",
		"parsimonious",
		"past",
		"pastoral",
		"pathetic",
		"peaceful",
		"penitent",
		"perfect",
		"periodic",
		"permissible",
		"perpetual",
		"petite",
		"petite",
		"phobic",
		"physical",
		"picayune",
		"pink",
		"piquant",
		"placid",
		"plain",
		"plant",
		"plastic",
		"plausible",
		"pleasant",
		"plucky",
		"pointless",
		"poised",
		"polite",
		"political",
		"poor",
		"possessive",
		"possible",
		"powerful",
		"precious",
		"premium",
		"present",
		"pretty",
		"previous",
		"pricey",
		"prickly",
		"private",
		"probable",
		"productive",
		"profuse",
		"protective",
		"proud",
		"psychedelic",
		"psychotic",
		"public",
		"puffy",
		"pumped",
		"puny",
		"purple",
		"purring",
		"pushy",
		"puzzled",
		"puzzling",
		"quack",
		"quaint",
		"quarrelsome",
		"questionable",
		"quick",
		"quickest",
		"quiet",
		"quirky",
		"quixotic",
		"quizzical",
		"rabid",
		"racial",
		"ragged",
		"rainy",
		"rambunctious",
		"rampant",
		"rapid",
		"rare",
		"raspy",
		"ratty",
		"ready",
		"real",
		"rebel",
		"receptive",
		"recondite",
		"red",
		"redundant",
		"reflective",
		"regular",
		"relieved",
		"remarkable",
		"reminiscent",
		"repulsive",
		"resolute",
		"resonant",
		"responsible",
		"rhetorical",
		"rich",
		"right",
		"righteous",
		"rightful",
		"rigid",
		"ripe",
		"ritzy",
		"roasted",
		"robust",
		"romantic",
		"roomy",
		"rotten",
		"rough",
		"round",
		"royal",
		"ruddy",
		"rude",
		"rural",
		"rustic",
		"ruthless",
		"sable",
		"sad",
		"safe",
		"salty",
		"same",
		"sassy",
		"satisfying",
		"savory",
		"scandalous",
		"scarce",
		"scared",
		"scary",
		"scattered",
		"scientific",
		"scintillating",
		"scrawny",
		"screeching",
		"second",
		"second-hand",
		"secret",
		"secretive",
		"sedate",
		"seemly",
		"selective",
		"selfish",
		"separate",
		"serious",
		"shaggy",
		"shaky",
		"shallow",
		"sharp",
		"shiny",
		"shivering",
		"shocking",
		"short",
		"shrill",
		"shut",
		"shy",
		"sick",
		"silent",
		"silent",
		"silky",
		"silly",
		"simple",
		"simplistic",
		"sincere",
		"six",
		"skillful",
		"skinny",
		"sleepy",
		"slim",
		"slimy",
		"slippery",
		"sloppy",
		"slow",
		"small",
		"smart",
		"smelly",
		"smiling",
		"smoggy",
		"smooth",
		"sneaky",
		"snobbish",
		"snotty",
		"soft",
		"soggy",
		"solid",
		"somber",
		"sophisticated",
		"sordid",
		"sore",
		"sore",
		"sour",
		"sparkling",
		"special",
		"spectacular",
		"spicy",
		"spiffy",
		"spiky",
		"spiritual",
		"spiteful",
		"splendid",
		"spooky",
		"spotless",
		"spotted",
		"spotty",
		"spurious",
		"squalid",
		"square",
		"squealing",
		"squeamish",
		"staking",
		"stale",
		"standing",
		"statuesque",
		"steadfast",
		"steady",
		"steep",
		"stereotyped",
		"sticky",
		"stiff",
		"stimulating",
		"stingy",
		"stormy",
		"straight",
		"strange",
		"striped",
		"strong",
		"stupendous",
		"stupid",
		"sturdy",
		"subdued",
		"subsequent",
		"substantial",
		"successful",
		"succinct",
		"sudden",
		"sulky",
		"super",
		"superb",
		"superficial",
		"supreme",
		"swanky",
		"sweet",
		"sweltering",
		"swift",
		"symptomatic",
		"synonymous",
		"taboo",
		"tacit",
		"tacky",
		"talented",
		"tall",
		"tame",
		"tan",
		"tangible",
		"tangy",
		"tart",
		"tasteful",
		"tasteless",
		"tasty",
		"tawdry",
		"tearful",
		"tedious",
		"teeny",
		"teeny-tiny",
		"telling",
		"temporary",
		"ten",
		"tender",
		"tense",
		"tense",
		"tenuous",
		"terrible",
		"terrific",
		"tested",
		"testy",
		"thankful",
		"therapeutic",
		"thick",
		"thin",
		"thinkable",
		"third",
		"thirsty",
		"thirsty",
		"thoughtful",
		"thoughtless",
		"threatening",
		"three",
		"thundering",
		"tidy",
		"tight",
		"tightfisted",
		"tiny",
		"tired",
		"tiresome",
		"toothsome",
		"torpid",
		"tough",
		"towering",
		"tranquil",
		"trashy",
		"tremendous",
		"tricky",
		"trite",
		"troubled",
		"truculent",
		"true",
		"truthful",
		"two",
		"typical",
		"ubiquitous",
		"ugliest",
		"ugly",
		"ultra",
		"unable",
		"unaccountable",
		"unadvised",
		"unarmed",
		"unbecoming",
		"unbiased",
		"uncovered",
		"understood",
		"undesirable",
		"unequal",
		"unequaled",
		"uneven",
		"unhealthy",
		"uninterested",
		"unique",
		"unkempt",
		"unknown",
		"unnatural",
		"unruly",
		"unsightly",
		"unsuitable",
		"untidy",
		"unused",
		"unusual",
		"unwieldy",
		"unwritten",
		"upbeat",
		"uppity",
		"upset",
		"uptight",
		"used",
		"useful",
		"useless",
		"utopian",
		"utter",
		"uttermost",
		"vacuous",
		"vagabond",
		"vague",
		"valuable",
		"various",
		"vast",
		"vengeful",
		"venomous",
		"verdant",
		"versed",
		"victorious",
		"vigorous",
		"violent",
		"violet",
		"vivacious",
		"voiceless",
		"volatile",
		"voracious",
		"vulgar",
		"wacky",
		"waggish",
		"waiting",
		"wakeful",
		"wandering",
		"wanting",
		"warlike",
		"warm",
		"wary",
		"wasteful",
		"watery",
		"weak",
		"wealthy",
		"weary",
		"well-groomed",
		"well-made",
		"well-off",
		"well-to-do",
		"wet",
		"whimsical",
		"whispering",
		"white",
		"whole",
		"wholesale",
		"wicked",
		"wide",
		"wide-eyed",
		"wiggly",
		"wild",
		"willing",
		"windy",
		"wiry",
		"wise",
		"wistful",
		"witty",
		"woebegone",
		"womanly",
		"wonderful",
		"wooden",
		"woozy",
		"workable",
		"worried",
		"worthless",
		"wrathful",
		"wretched",
		"wrong",
		"wry",
		"xenophobic",
		"yellow",
		"yielding",
		"young",
		"youthful",
		"yummy",
		"zany",
		"zealous",
		"zesty",
		"zippy",
		"zonked",
	}
)
